#pragma once

#include <iostream>
#include <iomanip>
#include <algorithm>
#include <vector>
#include <random>
#include <numeric>
#include <fstream>
#include <sstream>
#include <chrono>

using std::cout;
using std::cin;
using std::ifstream;
using std::ofstream;
using std::stringstream;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::fixed;
using std::setprecision;
using std::copy;
using std::swap;
using std::string;
using std::vector;
using std::accumulate;
using std::sort;